export enum ActionType {
	LoadInventory,
	AddInventory,
	DeleteInventory,
	AddCategory,
	SetStatsCategory,
	SetStatsAttribute,
	EditItemName,
	EditItemCategory,
	EditItemAttribute,
	SetItemToEdit,
	ValidateEditItem,
	EditCategoryName,
	EditCategoryAttribute,
	SetCategoryToEdit,
}
