export enum Actions {
	ADD_INVENTORY = 'ADD INVENTORY',
	REMOVE_INVENTORY = 'ADD INVENTORY',
	SET_ATTRIBUTE = 'SET ATTRIBUTE',

	ADD_CATEGORY = 'ADD CATEGORY',
	REMOVE_CATEGORY = 'REMOVE CATEGORY',
	EDIT_CATEGORY = 'EDIT CATEGORY',

	SET_FILTER = "SET FILTER",

	SET_CHART_ATTRIBUTE = "SET CHART ATTRIBUTE"
}